name: vorosoft
favicon: null
layout_spectrum: 0
typography_spectrum: 0.2026
title: vorosoft
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69563826-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#15181d'
    - '#2f3b2f'
    - '#d0cabc'
    - '#737f7f'
    - '#63453a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
