name: vorosoft
favicon: null
layout_spectrum: 0
typography_spectrum: 0.54697
title: vorosoft
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69563826-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#303030'
    - '#c4c6c5'
    - '#f788a8'
    - '#000000'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
